project:
  type: book
  output-dir: docs

book:
  title: "MetaDAG experiment example"
  author: ""
  date: "2023-6-6"
  chapters:
    - index.qmd
    - data_load.qmd
    - data_metadag_20230321_long_report.qmd
    - mDag_four_distance_comparison.qmd
    - graphs.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Journal
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    
editor: visual
