project:
  type: book
  output-dir: docs

book:
  title: "MetaDAG experiment example"
  author: ""
  date: "2023-6-6"
  chapters:
    - index.qmd
    - data_load.qmd
    - data_medag_20230321_long_report.qmd
    - kernel_1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Journal

editor: visual
